---
abstract: 'Normalize incoming Unicode parameters'
author:
  - 'John Barrett <john@jbrt.org>'
build_requires:
  Encode: '0'
  FindBin: '0'
  HTTP::Request::Common: '0'
  Plack::Test: '0'
  Test::More: '0'
  autodie: '0'
  charnames: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-UnicodeNormalize
requires:
  Carp: '0'
  Dancer2: '0.14300'
  Dancer2::Plugin: '0'
  Unicode::Normalize: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/jbarrett/Dancer2-Plugin-UnicodeNormalize
version: '0.033'
