---
abstract: 'Normalize incoming Unicode parameters'
author:
  - 'John Barrett <john@jbrt.org>'
build_requires:
  Dancer2::Test: 0
  Digest::MD5: 0
  Encode: 0
  FindBin: 0
  Test::More: 0
  autodie: 0
  charnames: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-UnicodeNormalize
requires:
  Carp: 0
  Dancer2: 0
  Dancer2::Plugin: 0
  Unicode::Normalize: 0
  strict: 0
  warnings: 0
version: 0.03
